---
name: Manual maven steps for CI
on:
    pull_request:
      branches: 
        - main
    workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write
  actions: read
  

jobs:
    manual:
        runs-on: ubuntu-24.04
        strategy:
          fail-fast: false
          matrix:
            java: [17, 21]

        steps:
          - uses: actions/checkout@v5

          - uses: actions/setup-java@v5
            with:
                distribution: 'temurin'
                java-version: ${{ matrix.java }}
                cache: maven

          - uses: jfrog/setup-jfrog-cli@v4
          # + Authentication method
          - run: jf --version

          - name: Initialize CodeQL
            uses: github/codeql-action/init@v3
            with:
              languages: java # Specify the language to analyze

                
          - name: build package
            run: mvn ${{ vars.GOAL  }}

          
          - name: Perform CodeQL Analysis
            uses: github/codeql-action/analyze@v3

          - name: publish test results
            uses: EnricoMi/publish-unit-test-result-action@v2
            with:
              files: |
                **/target/surefire-reports/*.xml

          
          - name: Uploading packaged jar files
            uses: actions/upload-artifact@v4
            with:
              name: spring-petclinic-jar-${{ matrix.java }}
              path: '**/target/*.jar'


